Add cutout bottom offset
juliuscanute/qr_code_scanner pull request #115
Opened 2020-07-23 19:02 UTC by BelfDev

This simple PR adds a property to `QrScannerOverlayShape` in order to customise the cutout vertical position.

2020-08-24 19:46 UTC, dspicher requested changes

2020-08-24 19:46 UTC, dspicher commented on example/lib/main.dart
> +                  cutOutBottomOffset: 24),
```suggestion
                  cutOutBottomOffset: 24,),
```
and `dartfmt` please.

2020-08-24 19:46 UTC, dspicher commented on lib/src/qr_scanner_overlay_shape.dart
> +      this.cutOutBottomOffset = 0})
```suggestion
      this.cutOutBottomOffset = 0,})
```
and `dartfmt` please.

2020-08-24 19:48 UTC, dspicher commented
Thanks for the PR! And sorry for the late response.

Can you please remove the two XCode-related files from the diff? The two commits could also be squashed into one. After this and the two small formatting nits above, this is good to go.

2020-08-24 19:48 UTC, BelfDev commented
> Thanks for the PR! And sorry for the late response.
> 
> Can you please remove the two XCode-related files from the diff? The two commits could also be squashed into one. After this and the two small formatting nits above, this is good to go.

Hey! Yes, sure. I'll get to it tomorrow morning. Cheers :)

2020-08-31 22:34 UTC, BelfDev commented
@dspicher done ✅

2020-11-07 22:01 UTC, BelfDev commented
@dspicher can we merge this? :)

2020-12-10 20:34 UTC, merged